name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2025-08-14-a

    name: Swift ${{ matrix.tag }}

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          swift-build: ${{ matrix.tag }}
          swift-version: ${{ matrix.branch }}

      - uses: actions/checkout@v4

      - run: swift build -v

